# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gateway

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OpenOrdersSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OpenOrdersSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOpenOrdersSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OpenOrdersSnapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OpenOrdersSnapshot
    def Orders(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from gateway.Order import Order
            obj = Order()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OpenOrdersSnapshot
    def OrdersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OpenOrdersSnapshot
    def OrdersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def OpenOrdersSnapshotStart(builder):
    builder.StartObject(1)

def Start(builder):
    OpenOrdersSnapshotStart(builder)

def OpenOrdersSnapshotAddOrders(builder, orders):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(orders), 0)

def AddOrders(builder, orders):
    OpenOrdersSnapshotAddOrders(builder, orders)

def OpenOrdersSnapshotStartOrdersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOrdersVector(builder, numElems):
    return OpenOrdersSnapshotStartOrdersVector(builder, numElems)

def OpenOrdersSnapshotEnd(builder):
    return builder.EndObject()

def End(builder):
    return OpenOrdersSnapshotEnd(builder)
